name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          docker --version
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ Secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: abhitesh003/wisecow:version1

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          kubectl version --client

      - name: Set up kubeconfig for Minikube on EC2
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG}}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config
          kubectl config view
          kubectl get nodes
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
      - name: Create or update TLS secret (wisecow-tls)
        run: |
         kubectl create secret tls wisecow-tls \
          --cert=<(echo "${{ secrets.TLS_CRT }}" | base64 -d) \
          --key=<(echo "${{ secrets.TLS_KEY }}" | base64 -d) \
          --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yml
          kubectl apply -f service.yml
          kubectl rollout status deployment/wisecow-deployment
         


